apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-app
  labels:
    app: flask-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-app
  template:
    metadata:
      labels:
        app: flask-hello-app
    spec:
      containers:
      - name: flask-hello-app
        image: pratikkorat/flask-hello-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "developmenthello"